### ISSUE TITLE
Add Airtable

### ISSUE THREAD

**Issue by KevinBatdorf** [instatushq/out#19]
Seems this would fit here?

Is it trivial to implement and test? I can give it a shot over the weekend if you'd like.

https://status.airtable.com/

**Comment by alisalahio** [comment]
Hi Kevin,
It's trivial if the product uses a service we already implemented (like Statuspage, Status.io, etc)
So, I just added it now :P

https://github.com/instatushq/out/commit/148458aa863ed3406d814cb4d792572a317340e8

Would love if you contribute over the weekend though (maybe with another thing) :D

**Comment by KevinBatdorf** [comment]
Awesome! 

> Would love if you contribute over the weekend though (maybe with another thing)

What do you have in mind?

**Comment by alisalahio** [comment]
Maybe if you use Azure or Google Cloud or any other service that's not added :D
