### ISSUE TITLE
Add Platform.sh

### ISSUE THREAD

**Issue by seanhamlin** [instatushq/out#22]
Status page is https://status.platform.sh/

**Comment by alisalahio** [comment]
Just added 🚀 https://github.com/instatushq/out/commit/ca7f7de536c4789a49e8f42ef8ad253d7ab56897

**Comment by seanhamlin** [comment]
I think their name is `Platform.sh` not `PlatformSH` (at least this is what their website has).

**Comment by alisalahio** [comment]
Yeah you're correct. PlatformSH is just an identifier. The user-facing name is in this file https://github.com/instatushq/out/blob/main/src/services/statuspage/platformsh.ts

I found that the file is already added but not imported :D

**Comment by seanhamlin** [comment]
Ah, thanks for clarifying!
