### ISSUE TITLE
Bitwarden and Hund-based services

### ISSUE THREAD

**Issue by franky47** [instatushq/out#28]
I use [Bitwarden](https://bitwarden.com) as my password manager. Their [status page](https://status.bitwarden.com/) is powered by [Hund](https://hund.io/), which unfortunately does not seem to have a simple JSON endpoint to ping for updates, but instead uses a [live event stream](https://hund.io/help/documentation/live-event-streams) of [Server-Sent Events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events).

In order to obtain the status from Hund-based services, there could be a few approaches:

### Approach A: following the SSE protocol
1. Open a long-running connection in the Service constructor
2. Listen to events with status updates
3. Cache the latest state from those events
4. Return the latest cached value in `updateStatus`

Pros:
- Minimises data transfer (status updates are sent every 5 minutes)
- Does not load the Hund servers with lots of connection requests

Cons:
- Long-connection may not play well with Out's inner workings (conjecture, I haven't dived deep in the architecture)
- Loss of network connection on the host may not reconnect easily (it does in `curl`, I haven't checked with Axios).

### Approach B: polling
1. Open a connection in `updateStatus`
2. Wait for it to return the current status for the service
3. Kill the connection (as it will not terminate on its own)
4. Parse and return the current status

Pros:
- Follows the rest of the Service implementations more closely (poll every 5 seconds)

Cons:
- Feels hacky
- Incurs load on the Hund servers
- Unnecessary data transfer

**Comment by alisalahio** [comment]
Hi @franky47, 

Thank you so much for the research you've done! 🔥

I personally prefer Approach B as:
- It matches the rest of the services
- I think 5 minutes is too long for the service to be useful
- I'm planning to make the poll time customizable, so that wouldn't work with Hund-based services if we follow Approach B

I'm OK with both approaches though.. If you're planning to implement this, feel free to go ahead with whatever you prefer 🚀

**Comment by franky47** [comment]
Note that the 5 minutes are the maximum time between "nothing changed" updates. I supposed (but haven't checked) that failures are reported in real time, in which case they'd be caught within the 5 seconds (max) of Out's polling.

**Comment by alisalahio** [comment]
Oh Ok that's awesome :D let's try either approach then :D

**Comment by franky47** [comment]
After leaving a connection open for a while, I did not get anymore status updates, so I guess solution B is indeed better, as this way we're sure not to miss anything. I'll see how I can kill the connection after the initial state is received, hopefully that can be done without adding extra dependencies.

**Comment by franky47** [comment]
Note: EventSource may not be the wisest choice for long-term maintenance, as it shows some lack of interest by the Chrome team and w3c. Examples include the inability to pass headers to the underlying request (which will be the subject of an upcoming PR):
https://github.com/whatwg/html/issues/2177
