### ISSUE TITLE
Suggestion: make window vertically resizable

### ISSUE THREAD

**Issue by franky47** [instatushq/out#31]
With my last two contributions I've maxed out the number of services I can display at a glance, and scrolling is so annoying 😅

It would be awesome if the window height could adapt to the maximum number of services. Unfortunately I have very little knowledge of Electron to propose a PR there, I don't even know if it's possible to programmatically resize the window.

**Comment by alisalahio** [comment]
Yeah I agree it'd be awesome :D
I wanted to do this but couldn't do it in a clean way. I'll try again :D

**Comment by alisalahio** [comment]
The man and legend @andreivreja just resolved this issue 🚀
