### ISSUE TITLE
What about Slack?

### ISSUE THREAD

**Issue by callmehanu** [instatushq/out#4]
I search it many times but I don't find slack on the list! 😐
https://status.slack.com/

**Comment by alisalahio** [comment]
They're using their own status service I think, so we'll need to have a custom implementation for it!

I know I used Slack specifically for the marketing video, but I didn't notice it's not really included, so I'm sorry for that..

Will be working on it soon!

**Comment by nblackburn** [comment]
@alisalahio Happy to take this now if you like?

**Comment by alisalahio** [comment]
That would be awesome! 
They don't have an API, but here's stts implementation, it could help lol

https://github.com/inket/stts/blob/master/stts/Services/Slack.swift

**Comment by nblackburn** [comment]
@alisalahio They do in fact have an API and I have it more or less implemented. Just doing some tests before send it across to you.

https://api.slack.com/docs/slack-status

**Comment by alisalahio** [comment]
Oh how did you discover this!! Thank you 🔥🔥

**Comment by nblackburn** [comment]
@alisalahio I have worked with Slack's API's in the past so know about it from digging around in the documentation.
