### ISSUE TITLE
Integrate with the main Instatus app for third-part components manually added

### ISSUE THREAD

**Issue by ajhalili2006** [instatushq/out#43]
We don't want to setup an web server where we do the scraping stuff on different status pages (Vercel, GitHub, Netlify, etc.) and feed back to Instatus API. Probably add an way to integrate this with the main Instatus app?

**Comment by alisalahio** [comment]
Yeah that would be awesome! 

I'll eventually work on that, but it's not related to Out as an app, so I'll close the issue

Great idea though, and I'll definitely work on it in the future!
