### ISSUE TITLE
Updating services is not hooked up

### ISSUE THREAD

**Issue by nblackburn** [instatushq/out#8]
I was looking into implementing a custom service and noticed the `updateStatus` method is not implemented. Unless I am otherwise mistaken this means the app doesn't actually do anything (at least at the moment).

See: https://github.com/instatushq/out/blob/main/src/services/service.ts#L12

**Comment by alisalahio** [comment]
The base updateStatus should be overridden.
Most services that use Statuspage, Status.io, etc inherit an updateStatus from these services, because they work the same way.
You'll find the implementations here: https://github.com/instatushq/out/blob/main/src/services/base

**Comment by nblackburn** [comment]
Sorry, was being an idiot. I have been staring at code all day and am starting to think it's time to take a break.

**Comment by alisalahio** [comment]
You're not at all :D 

I need a break too lol
